name: Docker Image CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

jobs:

   build-artifact:
    runs-on: ubuntu-latest
    env: 
      ECR_REGISTRY: 837232691946.dkr.ecr.us-east-2.amazonaws.com
      ECR_REPOSITORY: symphony-ecr-aws
      IMAGE_TAG: V1.0
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials for build and deploy ECR 15
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: login ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: path
        run: pwd

      - name: docker build graph
        run: docker build . --file ECR/symphony/graph/Dockerfile --tag golang:1.15-alpine  

      - name: docker images
        run: docker images

      - name: docker tag
        run: docker tag golang:1.15-alpine $ECR_REGISTRY/$ECR_REPOSITORY:graph_$IMAGE_TAG
      
      - name: docker push
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:graph_$IMAGE_TAG

