name: Docker Image CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

jobs:

        #build:

        #runs-on: ubuntu-latest

        #steps:
        #- uses: actions/checkout@v3
        #- name: Build the Docker image
        #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-artifact:
    runs-on: ubuntu-latest
    #needs: [lint, unit-test, sonarqube]
    env: 
      COMPOSE_FILE: ECR/symphony/integration/docker-compose.pr.yaml
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials for build and deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}         
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1
      - name: login ecr
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 837232691946.dkr.ecr.us-east-2.amazonaws.com
      - name: docker compose
        run: docker-compose build 
      - name: docker images
        run: docker images
      - name: docker tag
        run: docker tag integration_graph:latest 837232691946.dkr.ecr.us-east-2.amazonaws.com/symphony-ecr-aws:latest
      - name: docker push
        run: docker push 837232691946.dkr.ecr.us-east-2.amazonaws.com/symphony-ecr-aws:latest
